version: '3'

services:
  hostname:
    build:
      context: ./
      dockerfile: ./Dockerfile.v2
    image: akalipetis/flask-hostname:v2
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 3
