# This requires a network to be created in advance
# docker network create -d overlay --attachable mongonet
# Initialize the replica set by connecting and running
# rs.initiate( { _id : "my-replica-set", members: [ { _id : 0, host : "mongo-01:27017" } ]})
# Add members
# rs.add("mongo-02")
# rs.add("mongo-03")
version: '3'

services:
  mongo-01:
    command: mongod --replSet "my-replica-set"
    image: mongo:3.4
    networks:
      - mongonet
    volumes:
      - mongo01:/data/db
    deploy:
      placement:
        constraints:
          - node.hostname==node1
  mongo-02:
    command: mongod --replSet "my-replica-set"
    image: mongo:3.4
    networks:
      - mongonet
    volumes:
      - mongo02:/data/db
    deploy:
      placement:
        constraints:
          - node.hostname==node2
  mongo-03:
    command: mongod --replSet "my-replica-set"
    image: mongo:3.4
    networks:
      - mongonet
    volumes:
      - mongo03:/data/db
    deploy:
      placement:
        constraints:
          - node.hostname==node3

networks:
  mongonet:
    external: true

volumes:
  mongo01:
    external: true
  mongo02:
    external: true
  mongo03:
    external: true
